# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mainwindow.ui'
#
# Created: Tue Feb  3 17:51:55 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuDLX_Sim_MainWindow = QtGui.QMenu(self.menubar)
        self.menuDLX_Sim_MainWindow.setObjectName("menuDLX_Sim_MainWindow")
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuSimulator = QtGui.QMenu(self.menubar)
        self.menuSimulator.setObjectName("menuSimulator")
        self.menuPipeline = QtGui.QMenu(self.menubar)
        self.menuPipeline.setObjectName("menuPipeline")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.DW1 = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DW1.sizePolicy().hasHeightForWidth())
        self.DW1.setSizePolicy(sizePolicy)
        self.DW1.setObjectName("DW1")
        self.dockWindow_Contents_1 = QtGui.QWidget()
        self.dockWindow_Contents_1.setObjectName("dockWindow_Contents_1")
        self.programview = QtGui.QListView(self.dockWindow_Contents_1)
        self.programview.setGeometry(QtCore.QRect(0, 0, 300, 400))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.programview.sizePolicy().hasHeightForWidth())
        self.programview.setSizePolicy(sizePolicy)
        self.programview.setMinimumSize(QtCore.QSize(100, 400))
        self.programview.setUniformItemSizes(True)
        self.programview.setSelectionRectVisible(True)
        self.programview.setObjectName("programview")
        self.DW1.setWidget(self.dockWindow_Contents_1)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.DW1)
        self.DW2 = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DW2.sizePolicy().hasHeightForWidth())
        self.DW2.setSizePolicy(sizePolicy)
        self.DW2.setObjectName("DW2")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.pipeview = QtGui.QGraphicsView(self.dockWidgetContents_2)
        self.pipeview.setGeometry(QtCore.QRect(0, 0, 470, 400))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pipeview.sizePolicy().hasHeightForWidth())
        self.pipeview.setSizePolicy(sizePolicy)
        self.pipeview.setMinimumSize(QtCore.QSize(200, 400))
        self.pipeview.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pipeview.setObjectName("pipeview")
        self.DW2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.DW2)
        self.DW3 = QtGui.QDockWidget(MainWindow)
        self.DW3.setObjectName("DW3")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.registerview = QtGui.QListView(self.dockWidgetContents_3)
        self.registerview.setGeometry(QtCore.QRect(0, 0, 395, 100))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerview.sizePolicy().hasHeightForWidth())
        self.registerview.setSizePolicy(sizePolicy)
        self.registerview.setMinimumSize(QtCore.QSize(200, 100))
        self.registerview.setObjectName("registerview")
        self.DW3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.DW3)
        self.DW4 = QtGui.QDockWidget(MainWindow)
        self.DW4.setObjectName("DW4")
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.memoryview = QtGui.QListView(self.dockWidgetContents_4)
        self.memoryview.setGeometry(QtCore.QRect(0, 0, 395, 100))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memoryview.sizePolicy().hasHeightForWidth())
        self.memoryview.setSizePolicy(sizePolicy)
        self.memoryview.setMinimumSize(QtCore.QSize(200, 100))
        self.memoryview.setObjectName("memoryview")
        self.DW4.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.DW4)
        self.DW5 = QtGui.QDockWidget(MainWindow)
        self.DW5.setObjectName("DW5")
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.statisticsview = QtGui.QListView(self.dockWidgetContents_5)
        self.statisticsview.setGeometry(QtCore.QRect(0, 0, 800, 50))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statisticsview.sizePolicy().hasHeightForWidth())
        self.statisticsview.setSizePolicy(sizePolicy)
        self.statisticsview.setMinimumSize(QtCore.QSize(600, 50))
        self.statisticsview.setObjectName("statisticsview")
        self.DW5.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.DW5)
        self.action_LoadProgram = QtGui.QAction(MainWindow)
        self.action_LoadProgram.setObjectName("action_LoadProgram")
        self.action_ResetDLX = QtGui.QAction(MainWindow)
        self.action_ResetDLX.setObjectName("action_ResetDLX")
        self.action_ProgramView = QtGui.QAction(MainWindow)
        self.action_ProgramView.setCheckable(True)
        self.action_ProgramView.setChecked(True)
        self.action_ProgramView.setObjectName("action_ProgramView")
        self.action_PipelineView = QtGui.QAction(MainWindow)
        self.action_PipelineView.setCheckable(True)
        self.action_PipelineView.setChecked(False)
        self.action_PipelineView.setObjectName("action_PipelineView")
        self.action_MemoryView = QtGui.QAction(MainWindow)
        self.action_MemoryView.setCheckable(True)
        self.action_MemoryView.setObjectName("action_MemoryView")
        self.action_RegisterView = QtGui.QAction(MainWindow)
        self.action_RegisterView.setCheckable(True)
        self.action_RegisterView.setChecked(False)
        self.action_RegisterView.setObjectName("action_RegisterView")
        self.action_NextStep = QtGui.QAction(MainWindow)
        self.action_NextStep.setObjectName("action_NextStep")
        self.action_MoreSteps = QtGui.QAction(MainWindow)
        self.action_MoreSteps.setObjectName("action_MoreSteps")
        self.action_Run = QtGui.QAction(MainWindow)
        self.action_Run.setObjectName("action_Run")
        self.action_Forwarding = QtGui.QAction(MainWindow)
        self.action_Forwarding.setCheckable(True)
        self.action_Forwarding.setObjectName("action_Forwarding")
        self.action_MemorySize = QtGui.QAction(MainWindow)
        self.action_MemorySize.setObjectName("action_MemorySize")
        self.action_StatisticsView = QtGui.QAction(MainWindow)
        self.action_StatisticsView.setCheckable(True)
        self.action_StatisticsView.setObjectName("action_StatisticsView")
        self.menuDLX_Sim_MainWindow.addAction(self.action_LoadProgram)
        self.menuDLX_Sim_MainWindow.addAction(self.action_ResetDLX)
        self.menuWindow.addAction(self.action_ProgramView)
        self.menuWindow.addAction(self.action_PipelineView)
        self.menuWindow.addAction(self.action_MemoryView)
        self.menuWindow.addAction(self.action_RegisterView)
        self.menuWindow.addAction(self.action_StatisticsView)
        self.menuSimulator.addAction(self.action_NextStep)
        self.menuSimulator.addAction(self.action_MoreSteps)
        self.menuSimulator.addAction(self.action_Run)
        self.menuPipeline.addAction(self.action_Forwarding)
        self.menuPipeline.addAction(self.action_MemorySize)
        self.menubar.addAction(self.menuDLX_Sim_MainWindow.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuSimulator.menuAction())
        self.menubar.addAction(self.menuPipeline.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDLX_Sim_MainWindow.setTitle(QtGui.QApplication.translate("MainWindow", "DLX_Sim", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setTitle(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulator.setTitle(QtGui.QApplication.translate("MainWindow", "Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPipeline.setTitle(QtGui.QApplication.translate("MainWindow", "DLX", None, QtGui.QApplication.UnicodeUTF8))
        self.DW1.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Program View", None, QtGui.QApplication.UnicodeUTF8))
        self.DW2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Pipeline View (Clock Cycles)", None, QtGui.QApplication.UnicodeUTF8))
        self.DW3.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Register View", None, QtGui.QApplication.UnicodeUTF8))
        self.DW4.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Memory View", None, QtGui.QApplication.UnicodeUTF8))
        self.DW5.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.action_LoadProgram.setText(QtGui.QApplication.translate("MainWindow", "Load Program", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ResetDLX.setText(QtGui.QApplication.translate("MainWindow", "Reset DLX", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ProgramView.setText(QtGui.QApplication.translate("MainWindow", "Program", None, QtGui.QApplication.UnicodeUTF8))
        self.action_PipelineView.setText(QtGui.QApplication.translate("MainWindow", "Pipeline", None, QtGui.QApplication.UnicodeUTF8))
        self.action_MemoryView.setText(QtGui.QApplication.translate("MainWindow", "Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.action_RegisterView.setText(QtGui.QApplication.translate("MainWindow", "Registers", None, QtGui.QApplication.UnicodeUTF8))
        self.action_NextStep.setText(QtGui.QApplication.translate("MainWindow", "Next Step", None, QtGui.QApplication.UnicodeUTF8))
        self.action_MoreSteps.setText(QtGui.QApplication.translate("MainWindow", "More Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Run.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Forwarding.setText(QtGui.QApplication.translate("MainWindow", "Forwarding", None, QtGui.QApplication.UnicodeUTF8))
        self.action_MemorySize.setText(QtGui.QApplication.translate("MainWindow", "Memory Size", None, QtGui.QApplication.UnicodeUTF8))
        self.action_StatisticsView.setText(QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))

