# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Dec 11 00:40:01 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuDLX_Sim_MainWindow = QtGui.QMenu(self.menubar)
        self.menuDLX_Sim_MainWindow.setObjectName("menuDLX_Sim_MainWindow")
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuSimulator = QtGui.QMenu(self.menubar)
        self.menuSimulator.setObjectName("menuSimulator")
        self.menuPipeline = QtGui.QMenu(self.menubar)
        self.menuPipeline.setObjectName("menuPipeline")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.DW1 = QtGui.QDockWidget(MainWindow)
        self.DW1.setObjectName("DW1")
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.DW1)
        self.DW2 = QtGui.QDockWidget(MainWindow)
        self.DW2.setObjectName("DW2")
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.DW2)
        self.DW3 = QtGui.QDockWidget(MainWindow)
        self.DW3.setObjectName("DW3")
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.DW3)
        self.action_LoadProgram = QtGui.QAction(MainWindow)
        self.action_LoadProgram.setObjectName("action_LoadProgram")
        self.action_ResetDLX = QtGui.QAction(MainWindow)
        self.action_ResetDLX.setObjectName("action_ResetDLX")
        self.action_ProgramView = QtGui.QAction(MainWindow)
        self.action_ProgramView.setCheckable(True)
        self.action_ProgramView.setChecked(True)
        self.action_ProgramView.setObjectName("action_ProgramView")
        self.action_PipelineView = QtGui.QAction(MainWindow)
        self.action_PipelineView.setCheckable(True)
        self.action_PipelineView.setChecked(True)
        self.action_PipelineView.setObjectName("action_PipelineView")
        self.action_MemoryView = QtGui.QAction(MainWindow)
        self.action_MemoryView.setCheckable(True)
        self.action_MemoryView.setObjectName("action_MemoryView")
        self.action_RegisterView = QtGui.QAction(MainWindow)
        self.action_RegisterView.setCheckable(True)
        self.action_RegisterView.setChecked(True)
        self.action_RegisterView.setObjectName("action_RegisterView")
        self.action_NextStep = QtGui.QAction(MainWindow)
        self.action_NextStep.setObjectName("action_NextStep")
        self.action_MoreSteps = QtGui.QAction(MainWindow)
        self.action_MoreSteps.setObjectName("action_MoreSteps")
        self.action_Run = QtGui.QAction(MainWindow)
        self.action_Run.setObjectName("action_Run")
        self.action_Forwarding = QtGui.QAction(MainWindow)
        self.action_Forwarding.setCheckable(True)
        self.action_Forwarding.setObjectName("action_Forwarding")
        self.action_MemorySize = QtGui.QAction(MainWindow)
        self.action_MemorySize.setObjectName("action_MemorySize")
        self.action_StatisticsView = QtGui.QAction(MainWindow)
        self.action_StatisticsView.setCheckable(True)
        self.action_StatisticsView.setObjectName("action_StatisticsView")
        self.menuDLX_Sim_MainWindow.addAction(self.action_LoadProgram)
        self.menuDLX_Sim_MainWindow.addAction(self.action_ResetDLX)
        self.menuWindow.addAction(self.action_ProgramView)
        self.menuWindow.addAction(self.action_PipelineView)
        self.menuWindow.addAction(self.action_MemoryView)
        self.menuWindow.addAction(self.action_RegisterView)
        self.menuWindow.addAction(self.action_StatisticsView)
        self.menuSimulator.addAction(self.action_NextStep)
        self.menuSimulator.addAction(self.action_MoreSteps)
        self.menuSimulator.addAction(self.action_Run)
        self.menuPipeline.addAction(self.action_Forwarding)
        self.menuPipeline.addAction(self.action_MemorySize)
        self.menubar.addAction(self.menuDLX_Sim_MainWindow.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuSimulator.menuAction())
        self.menubar.addAction(self.menuPipeline.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDLX_Sim_MainWindow.setTitle(QtGui.QApplication.translate("MainWindow", "DLX_Sim", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setTitle(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulator.setTitle(QtGui.QApplication.translate("MainWindow", "Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPipeline.setTitle(QtGui.QApplication.translate("MainWindow", "DLX", None, QtGui.QApplication.UnicodeUTF8))
        self.action_LoadProgram.setText(QtGui.QApplication.translate("MainWindow", "Load Program", None, QtGui.QApplication.UnicodeUTF8))
        self.action_LoadProgram.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ResetDLX.setText(QtGui.QApplication.translate("MainWindow", "Reset DLX", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ResetDLX.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ProgramView.setText(QtGui.QApplication.translate("MainWindow", "Program", None, QtGui.QApplication.UnicodeUTF8))
        self.action_PipelineView.setText(QtGui.QApplication.translate("MainWindow", "Pipeline", None, QtGui.QApplication.UnicodeUTF8))
        self.action_MemoryView.setText(QtGui.QApplication.translate("MainWindow", "Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.action_RegisterView.setText(QtGui.QApplication.translate("MainWindow", "Registers", None, QtGui.QApplication.UnicodeUTF8))
        self.action_NextStep.setText(QtGui.QApplication.translate("MainWindow", "Next Step", None, QtGui.QApplication.UnicodeUTF8))
        self.action_NextStep.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.action_MoreSteps.setText(QtGui.QApplication.translate("MainWindow", "More Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.action_MoreSteps.setShortcut(QtGui.QApplication.translate("MainWindow", "F6", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Run.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Run.setShortcut(QtGui.QApplication.translate("MainWindow", "F7", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Forwarding.setText(QtGui.QApplication.translate("MainWindow", "Forwarding", None, QtGui.QApplication.UnicodeUTF8))
        self.action_MemorySize.setText(QtGui.QApplication.translate("MainWindow", "Memory Size", None, QtGui.QApplication.UnicodeUTF8))
        self.action_StatisticsView.setText(QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))

